---
title: 'Figure S7: Ordination IWW colored by region'
author: "Sofie Zacho Vestergaard"
date: "2024-01-03"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
library(ampvis2)
library(tidyverse)
library(patchwork)
library(vegan)
library(ggtext)
```

```{r}

d <- amp_load(otutable = 'data/ASV_table_combined.tsv',
              taxonomy = 'data/ASVs_combined_MiDAS5.2.R1.sintax',
              metadata = 'data/metadata.xlsx',
              pruneSingletons = T) # remove singletons

# merge replicates
d_rep <- amp_merge_replicates(d, 
                              merge_var = "SampleID_replicates", 
                              round = 'up')

d_rep$metadata <- d_rep$metadata %>%
  rename(SampleID = SampleID_replicates)

d_rep_filt_iww <- amp_subset_samples(d_rep,
                                    SampleContent %in% 'AS',
                                    minreads = 50000, removeAbsentOTUs = F)


set.seed(22)
# rarefy
d_rare_iww <- amp_rarefy(d_rep_filt_iww, rarefy = 50000) # 10 000

diwwn <- normaliseTo100(d_rare_iww)
diwwn <- amp_subset_samples(diwwn, removeAbsentOTUs = T)

```

##import corecrat list
```{r}
growth_fate <- readxl::read_excel("output/DatasetS3.xlsx")

growing_ASV <- growth_fate %>% filter(growth_fate == 'growing') %>% pull(ASV)
corecrat_ASV <- readxl::read_excel("output/core&crat_ASV.xlsx") %>% filter(!Category %in% 'CRAT')
core_ASVs <- corecrat_ASV$OTU # Core 

cg <- intersect(growing_ASV, core_ASVs)

diwwn_growing <- amp_filter_taxa(d_rare_iww, tax_vector = core_ASVs, normalise = F)
diwwn_growing <- amp_subset_samples(diwwn_growing, removeAbsentOTUs = T, minreads = 10) %>% 
  normaliseTo100(.)

# how much cumulative abundance these growing ASV make up in influent
colSums(diwwn_growing$abund) %>% mean()
```


# Make continous metadata variables (PE + industrial load) into categories
```{r}
diwwn_growing$metadata <- diwwn_growing$metadata %>% 
  mutate(Ind_text = case_when(
    `IndustrialLoad[%]` == 0 ~ "None",
    `IndustrialLoad[%]` > 0 & `IndustrialLoad[%]` <= 10 ~ "Very Low",
    `IndustrialLoad[%]` > 10 & `IndustrialLoad[%]` <= 30 ~ "Low",
    `IndustrialLoad[%]` > 30 & `IndustrialLoad[%]` <= 50 ~ "Medium",
    `IndustrialLoad[%]` > 50 & `IndustrialLoad[%]` < 100 ~ "High",
    TRUE ~ NA_character_  # For any values that don't match the above conditions
  ),
  PEdesign_text = case_when(
    PEdesign <= 25000 ~ "Small",
    PEdesign > 25000 & PEdesign <= 100000 ~ "Medium",
    PEdesign > 100000 ~ "Large",
    TRUE ~ NA_character_  # For any values that don't match the above conditions
  ))



```




#PCoA parameters: Region, Design, PE, Industrial load

```{r}


pcoa_iww_bray <- amp_ordinate(diwwn,
                             type = 'PCoA',
                             distmeasure = "bray",
                             transform = 'none',
                             filter_species = 0
) 


```


##Adonis
```{r}
# make distance matrix
dist_matrix_bray <- vegdist(t(diwwn$abund), method = "bray")

# Region
adonis_reg <- adonis2(dist_matrix_bray ~ Region, data = diwwn$metadata)

```


##plots
```{r}

atex= 6.5
atit = 6.5

#Region
pcoa_iww_bray$data$Region <- factor(pcoa_iww_bray$data$Region, levels = c("Northern", "Central", "Southern", "Funen", "Zealand"))

p_region <- ggplot(pcoa_iww_bray$data, aes(x = PCo1, y = PCo2)) +
  geom_point(aes(fill = Region), size=1.8, shape = 21, alpha = 1)+
  #ylim(-0.34,0.34)+
  labs(x = pcoa_iww_bray$labels$x, y = pcoa_iww_bray$labels$y) +
  theme_bw() +
  theme(axis.text = element_text(size = atex, color = "black"),
        axis.title = element_text(color = "black", face = 'bold', size = atit),
        plot.title = element_text(hjust = 0.5, vjust = 0.5),
        legend.position = 'top',
        legend.title = element_text(face = 'bold', size = 7),
        legend.text = element_text(size = 6),
        plot.tag = element_text(face = 'bold', size = 10),
        legend.margin = margin(0, 0, -5, 0),
        legend.key.size = unit(0.2, "cm")) +
  guides(fill=guide_legend(title.position="top", 
                           title.hjust =0.5,
                           nrow = 2)) +
  geom_richtext( 
           x=0.22, y=0.4, 
           size = unit(1.8, "pt"),
           fontface="bold",
           label.padding = grid::unit(rep(0.8, 4), "pt"),
           label=paste("R\u00b2 =", round(adonis_reg$R2[[1]], 2), "<br>p-value =", adonis_reg$`Pr(>F)`[[1]]),
           color="black") +
  scale_fill_brewer(palette="RdYlBu")


ggsave(filename="output/FigS7_PCoA_iww_Region.png", 
       p_region,
       width=4, height=4,
       dpi = 320)

ggsave(filename="output/FigS7_PCoA_iww_Region.pdf", 
       p_region,
       width=4, height=4, useDingbats=FALSE, limitsize=FALSE)


```




# Add on (for growing only)
```{r}

diwwn_growing <- amp_filter_taxa(d_rare_iww, tax_vector = growing_ASV, normalise = F)
diwwn_growing <- amp_subset_samples(diwwn_growing, removeAbsentOTUs = T, minreads = 500) 

##plot basic PCoA
pcoa_iww_bray_grow <- amp_ordinate(diwwn_growing,
                             type = 'PCoA',
                             distmeasure = "bray",
                             transform = 'none',
                             filter_species = 0
) 

# make distance matrix
dist_matrix_bray_grow <- vegdist(t(diwwn_growing$abund), method = "bray")

# Region
adonis_reg_grow <- adonis2(dist_matrix_bray_grow ~ Region, data = diwwn_growing$metadata)


#Region
pcoa_iww_bray_grow$data$Region <- factor(pcoa_iww_bray_grow$data$Region, levels = c("Northern", "Central", "Southern", "Funen", "Zealand"))

p_region <- ggplot(pcoa_iww_bray_grow$data, aes(x = PCo1, y = PCo2)) +
  geom_point(aes(fill = Region), size=1.8, shape = 21, alpha = 1)+
  #ylim(-0.34,0.34)+
  labs(x = pcoa_iww_bray_grow$labels$x, y = pcoa_iww_bray_grow$labels$y) +
  theme_bw() +
  theme(axis.text = element_text(size = atex, color = "black"),
        axis.title = element_text(color = "black", face = 'bold', size = atit),
        plot.title = element_text(hjust = 0.5, vjust = 0.5),
        legend.position = 'top',
        legend.title = element_text(face = 'bold', size = 7),
        legend.text = element_text(size = 6),
        plot.tag = element_text(face = 'bold', size = 10),
        legend.margin = margin(0, 0, -5, 0),
        legend.key.size = unit(0.2, "cm")) +
  guides(fill=guide_legend(title.position="top", 
                           title.hjust =0.5,
                           nrow = 2)) +
  geom_richtext( 
           x=0, y=0, 
           size = unit(1.8, "pt"),
           fontface="bold",
           label.padding = grid::unit(rep(0.8, 4), "pt"),
           label=paste("R\u00b2 =", round(adonis_reg_grow$R2[[1]], 2), "<br>p-value =", adonis_reg_grow$`Pr(>F)`[[1]]),
           color="black") +
  scale_fill_brewer(palette="RdYlBu")


ggsave(filename="output/FigXX_PCoA_iww_Region_grow_500.png", 
       p_region,
       width=4, height=4,
       dpi = 320)

ggsave(filename="output/FigS7_PCoA_iww_Region_grow.pdf", 
       p_region,
       width=4, height=4, useDingbats=FALSE, limitsize=FALSE)

```


```{r}
h <- amp_heatmap(diwwn_growing,
                 normalise = F,
                 group_by = 'SampleSite',
                 tax_aggregate = 'Species',
                 tax_show = 25,
                 facet_by = 'Region',
                 plot_values_size = 2)
```

